name: Build and Push Docker Image to GHCR

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get Latest FRP Version
        id: get_version
        run: |
          LATEST_URL=$(curl -s -L -o /dev/null -w '%{url_effective}' https://github.com/fatedier/frp/releases/latest)
          VERSION=$(echo $LATEST_URL | grep -oE 'v[0-9]+\.[0-9]+\.[0-9]+')
          echo "FRP_VERSION=$VERSION" >> $GITHUB_ENV

      - name: Set Docker Image Repository Name
        run: |
          echo "REPO_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ env.REPO_NAME }}:latest
            ghcr.io/${{ env.REPO_NAME }}:${{ env.FRP_VERSION }}
          build-args: |
            FRP_VERSION=${{ env.FRP_VERSION }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
