name: Build and Push FRPS to GHCR
on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get repo info (lowercase)
        id: repo
        run: |
          owner=$(echo "${GITHUB_REPOSITORY_OWNER}" | tr '[:upper:]' '[:lower:]')
          repo=$(basename "${GITHUB_REPOSITORY}" | tr '[:upper:]' '[:lower:]')
          echo "owner=${owner}" >> $GITHUB_OUTPUT
          echo "repo=${repo}" >> $GITHUB_OUTPUT

      - name: Resolve latest frp version
        id: latest
        run: |
          url=$(curl -fsSLI -o /dev/null -w '%{url_effective}' https://github.com/fatedier/frp/releases/latest)
          tag="${url##*/}"         # v0.65.0
          ver="${tag#v}"           # 0.65.0
          echo "tag=${tag}" >> $GITHUB_OUTPUT
          echo "ver=${ver}" >> $GITHUB_OUTPUT
          echo "Latest tag: $tag"

      - name: Download frps (linux amd64)
        run: |
          tag=${{ steps.latest.outputs.tag }}
          ver=${{ steps.latest.outputs.ver }}
          tarball="frp_${ver}_linux_amd64.tar.gz"
          dlurl="https://github.com/fatedier/frp/releases/download/${tag}/${tarball}"
          curl -fL --retry 5 -o "${tarball}" "${dlurl}"
          tar -xzf "${tarball}"
          mv "frp_${ver}_linux_amd64/frps" ./frps
          chmod +x ./frps

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64
          tags: |
            ghcr.io/${{ steps.repo.outputs.owner }}/${{ steps.repo.outputs.repo }}:${{ steps.latest.outputs.tag }}
            ghcr.io/${{ steps.repo.outputs.owner }}/${{ steps.repo.outputs.repo }}:latest
